### ISSUE TITLE
报错[Error]  当前系统为   不在支持的系统列表内，安装中断  

### ISSUE THREAD

**Issue by itsScopion** [wulabing/SSR-manyuser_glzjin_shell#1]
RT
使用的是supervisor版
执行source /etc/os-release会显示No such file or directory
系统是CentOS release 6.9 (Final)

**Comment by wulabing** [comment]
supervisor版 暂时未支持 Centos6 系统，我会在明天适配一下 Centos 6

**Comment by itsScopion** [comment]
谢谢。
这个脚本挺方便的，很好用。
加油。

**Comment by wulabing** [comment]
已经进行了一部分修改，现在应该可以了。请重新下载然后尝试

**Comment by nick0425** [comment]
很棒的脚本！
